### PR TITLE
Added build and update versions scripts. Also udpated elm-package.jso…

### PR DESCRIPTION
**Pull request by oakesja**
…n so things will actually compile

### CODE REVIEW

**Comment by indigobiosystems-buildfu** [comment]
Triggered build

**Comment by indigobiosystems-buildfu** [comment]
Build started for 36f38de7eaa312be2933f62e5a190f114678169e

**Comment by indigobiosystems-buildfu** [comment]
Build finished. No test results found.

**Comment by oakesja** [comment]
retest this please

**Comment by indigobiosystems-buildfu** [comment]
Triggered build

**Comment by indigobiosystems-buildfu** [comment]
Build started for 36f38de7eaa312be2933f62e5a190f114678169e

**Comment by indigobiosystems-buildfu** [comment]
Build finished. No test results found.

**Comment by oakesja** [comment]
retest this please

**Comment by oakesja** [comment]
retest this please

**Comment by oakesja** [comment]
retest this please

**Comment by oakesja** [comment]
Should be into develop. See https://github.com/indigobio/elm-graphql/pull/2

**Pull request closed without merging**
